<div class="main">
    @foreach ($collection as $item)
    @if ($item->style_id === 1)
    @include('components.template.style1')
    @elseif ($item->style_id === 2)
    @include('components.template.style2')
    @elseif ($item->style_id === 3)
    @include('components.template.style3')
    @elseif ($item->style_id === 4)
    @include('components.template.style4')
    @elseif ($item->style_id === 5)
    @include('components.template.style5')
    @elseif ($item->style_id === 6)
    @include('components.template.style6')
    @elseif ($item->style_id === 7)
    @include('components.template.style7')
    @elseif ($item->style_id === 8)
    @include('components.template.style8')
    @elseif ($item->style_id === 9)
    @include('components.template.style9')
    @elseif ($item->style_id === 10)
    @include('components.template.style10')
    @elseif ($item->style_id === 11)
    @include('components.template.style11')
    @elseif ($item->style_id === 12)
    @include('components.template.style12')
    @elseif ($item->style_id === 13)
    @include('components.template.style13')
    @endif
    @endforeach
</div>
